### PR TITLE
Show EU not allowed channel to be inverted

### PR DESCRIPTION
**Pull request by schwabe**
Preview:

screenshot_x9d _17-08-25_14-17-31
screenshot_x9d _17-08-25_14-17-04

Allows to see which channels are legal in EU with a quick glance.

### CODE REVIEW

**Comment by schwabe** [comment]
screenshot_x9d _17-08-25_16-46-13

Remove artefacts :)

**Comment by mlametta** [comment]
If these changes were to be added maybe it would be a good idea to keep a separate 'EU' version as these changes wouldn't pertain to a 'US' version.

**Comment by nmaggioni** [comment]
Love the idea!

Maybe [these lines](https://github.com/darsor/opentx-frequency-chart/pull/2/files#diff-f8aeb1a3c2658bcf5ca0ee031e0b2ca1R10) could be left commented as @mlametta hinted, and a note about decommenting them added to the [main README](https://github.com/darsor/opentx-frequency-chart/blob/2de8bcefae34756e7f0721025f9f8b8c40d748ad/README.md). Maintaining two branches/files would be unnecessarily complex at this point IMO.

**Comment by darsor** [comment]
I fixed a couple more visual artifacts on the position screens and the X7 frequency screen. I also left the two lines commented out by default.

Thanks @schwabe for implementing this, and thanks @mlametta and @nmaggioni for the easy integration ideas.

**Pull request merged**
